package modelo.enumerates;

public enum Anomalia {
    COLISION_VEHICULAR,
    CONGESTION_VEHICULAR,
    DESARROLLO_DE_OBRA_PUBLICA,
    DERRAMES_SUSTANCIAS_PELIGROSAS_CARRETERA,
    INCENDIO,
    PRESENCIA_HUMO,
    PRESENCIA_GASES,
    ACCIDENTE_GRAVE,
    PRESENCIA_AMBULANCIAS_ESTADO_EMERGENCIA;
}